# Travis CI Configuration File

sudo: false
dist: trusty

# Tell Travis CI we're using PHP
language: php

# Caching to improve build times.
cache:
  apt: true
  directories:
    - node_modules
    - vendor
    - composer
    - $HOME/.npm
    - $HOME/.composer/cache


# PHP version used in first build configuration.
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

# WordPress version used in first build configuration.
env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.8 WP_MULTISITE=0
    - WP_VERSION=4.8 WP_MULTISITE=1
    - WP_VERSION=4.7 WP_MULTISITE=0
    - WP_VERSION=4.7 WP_MULTISITE=1
    - WP_VERSION=4.6 WP_MULTISITE=0
    - WP_VERSION=4.6 WP_MULTISITE=1

install:
  - curl -s http://getcomposer.org/installer | php

before_script:
  - |
      if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
        phpenv config-rm xdebug.ini
      else
        echo "xdebug.ini does not exist"
      fi
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - |
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
        composer global require "phpunit/phpunit=5.7.*"
      else
        composer global require "phpunit/phpunit=4.8.*"
      fi
  - composer require satooshi/php-coveralls '~1.0'
  - composer global require wp-coding-standards/wpcs
  - phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
#  - npm install -g grunt-cli
#  - npm install

script:
  - phpcs -p -s -n . --standard=./ruleset.xml --extensions=php
  - jscs -c .jscsrc .
  - jshint .
  - phpunit --coverage-clover=build/logs/clover.xml
#  - grunt test --verbose

after_success:
  - travis_retry php vendor/bin/coveralls --verbose --exclude-no-stmt
