# Travis CI Configuration File

sudo: false

# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

# WordPress version used in first build configuration.
env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.0 WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=1
    - WP_VERSION=4.1 WP_MULTISITE=0
    - WP_VERSION=4.1 WP_MULTISITE=1
    - WP_VERSION=4.2 WP_MULTISITE=0
    - WP_VERSION=4.2 WP_MULTISITE=1
    - WP_VERSION=4.3 WP_MULTISITE=0
    - WP_VERSION=4.3 WP_MULTISITE=1
    - WP_VERSION=4.4 WP_MULTISITE=0
    - WP_VERSION=4.4 WP_MULTISITE=1
    - WP_VERSION=4.5 WP_MULTISITE=0
    - WP_VERSION=4.5 WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit --coverage-clover=coverage.xml