workflows:
  version: 2
  tests:
    jobs:
    - php56-wp-latest-build
    - php56-wp48-build
    - php56-wp47-build
    - php70-wp-latest-build
    - php70-wp48-build
    - php70-wp47-build
    - php71-wp-latest-build
    - php71-wp48-build
    - php71-wp47-build
    - php72-wp-latest-build
    - php72-wp48-build
    - php72-wp47-build
    - php-lint
    - js-lint

version: 2

job-references:
  mysql_image: &mysql_image
                 circleci/mysql:5.6

  setup_environment: &setup_environment
    name: "Setup Environment Variables"
    command: |
      echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $BASH_ENV
      source /home/circleci/.bashrc

  install_dependencies: &install_dependencies
    name: "Install Dependencies"
    command: |
      sudo docker-php-ext-install mysqli

  install_wp_core: &install_wp_core
    name: "Install WordPress Core"
    command: |
      rm -rf /tmp/wordpress-tests-lib /tmp/wordpress
      bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION

  php_job: &php_job
    environment:
    - WP_VERSION: "latest"
    steps:
    - checkout
    - run: *setup_environment
    - run: *install_dependencies
    - run: *install_wp_core
    - run:
        name: "Run PHPUnit on Single Site"
        command: |
          phpunit --coverage-clover=build/logs/clover.xml
    - run:
        name: "Run PHPUnit on Multi Site"
        command: |
          WP_MULTISITE=1 phpunit --coverage-clover=build/logs/clover.xml
    - run:
        name: "Run PHP Parallel Lint"
        command: |
          parallel-lint --blame --exclude node_modules --exclude vendor .

jobs:
  php56-wp-latest-build:
    <<: *php_job
    docker:
    - image: pojome/php-cli:5.6
    - image: *mysql_image

  php56-wp48-build:
    <<: *php_job
    environment:
    - WP_VERSION: "4.8"
    docker:
    - image: pojome/php-cli:5.6
    - image: *mysql_image

  php56-wp47-build:
    <<: *php_job
    environment:
    - WP_VERSION: "4.7"
    docker:
    - image: pojome/php-cli:5.6
    - image: *mysql_image

  php70-wp-latest-build:
    <<: *php_job
    docker:
    - image: pojome/php-cli:7.0
    - image: *mysql_image

  php70-wp48-build:
    <<: *php_job
    environment:
    - WP_VERSION: "4.8"
    docker:
    - image: pojome/php-cli:7.0
    - image: *mysql_image

  php70-wp47-build:
    <<: *php_job
    environment:
    - WP_VERSION: "4.7"
    docker:
    - image: pojome/php-cli:7.0
    - image: *mysql_image

  php71-wp-latest-build:
    <<: *php_job
    docker:
    - image: pojome/php-cli:7.1
    - image: *mysql_image

  php71-wp48-build:
    <<: *php_job
    environment:
    - WP_VERSION: "4.8"
    docker:
    - image: pojome/php-cli:7.1
    - image: *mysql_image

  php71-wp47-build:
    <<: *php_job
    environment:
    - WP_VERSION: "4.7"
    docker:
    - image: pojome/php-cli:7.1
    - image: *mysql_image

  php72-wp-latest-build:
    <<: *php_job
    docker:
    - image: pojome/php-cli:7.2
    - image: *mysql_image

  php72-wp48-build:
    <<: *php_job
    environment:
    - WP_VERSION: "4.8"
    docker:
    - image: pojome/php-cli:7.2
    - image: *mysql_image

  php72-wp47-build:
    <<: *php_job
    environment:
    - WP_VERSION: "4.7"
    docker:
    - image: pojome/php-cli:7.2
    - image: *mysql_image

  js-lint:
    docker:
    - image: pojome/php-js-lints
    steps:
    - checkout
    - run:
        name: "Run JS lint"
        command: |
          jscs -c .jscsrc .
          jshint .

  php-lint:
    docker:
    - image: pojome/php-js-lints
    steps:
    - checkout
    - run:
        name: "Run PHP lint"
        command: |
          export PATH=$HOME/.composer/vendor/bin:$PATH
          phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
          phpcs -p -s -n . --standard=./ruleset.xml --extensions=php
