blank_issues_enabled: false
contact_links:
    - name: ğŸ›Ÿ Get Personal Support
      url: https://elemn.to/support-ticket
      about: Need help, guidance, or personal support? Follow these steps to get assistance from Elementor Support.
    - name: ğŸš€ Feature Requests
      url: https://elemn.to/gh-feature-requests
      about: Have an idea to improve Elementor? Submit your feature request here.
    - name: ğŸ§ª Editor V4 Discussions
      url: https://elemn.to/editor-v4-feedback
      about: Share your feedback, ideas, and thoughts about Editor V4's features.
    - name: ğŸ“š Visit the Developers Center
      url: https://elemn.to/dev-center
      about: Get technical documentation and resources to extend Elementor with custom code and integrations.
    - name: ğŸ“– Contribution Guidelines
      url: https://elemn.to/gh-contributing
      about: Before submitting a bug report, feature request, or pull request, please read our Contribution Guidelines.
    - name: ğŸ¤ Code of Conduct
      url: https://elemn.to/gh-code-of-conduct
      about: Help us maintain a safe, open, and welcoming environment by following our Code of Conduct.
