blank_issues_enabled: false
contact_links:
  - name: â“ Support Question
    url: https://wordpress.org/support/plugin/elementor/
    about: Elementor users who need assistant and have general usage questions.
  - name: â“ Elementor Support
    url: https://elementor.com/support/
    about: Customer experience for Elementor Pro users having questions or seeking general support.
  - name: â“ Elementor Community Support
    url: https://www.facebook.com/groups/Elementors/
    about: Users looking for help and support from the Elementor community.
  - name: ğŸ“ Elementor Documentation
    url: https://elementor.com/help/
    about: Information and documentation about Elementor.
  - name: ğŸ“ Elementor Developers
    url: https://developers.elementor.com/
    about: Technical information and Elementor developers docs.
