blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature Request
    url: https://github.com/orgs/elementor/discussions/new?category=feature-request
    about: Suggest new ideas, features, or enhancements
  - name: â“ Support Question
    url: https://wordpress.org/support/plugin/elementor/
    about: For Elementor users who need assistant and have general usage questions.
  - name: ğŸ’ Elementor Pro Support
    url: https://elementor.com/support/
    about: If you have an active Elementor Pro license you are entitled to personal support, please see your purchase email or visit your Elementor Account page for details.
  - name: ğŸ—¨ï¸ Elementor Global Community
    url: https://www.facebook.com/groups/Elementors/
    about: The main Facebook group where all kinds of users come together to help each other.
  - name: ğŸ“ Elementor Academy
    url: https://elementor.com/academy/
    about: Learn everything you need to know about using Elementor.
  - name: ğŸ“š Elementor Developers Documentation
    url: https://developers.elementor.com/
    about: Technical information and Elementor developers docs. Learn everything about our Developer-API.
