name: Push New Version
description: Git push the new version to the remote repository.

inputs:
  MAINTAIN_USERNAME:
    required: true
  MAINTAIN_EMAIL:
    required: true
  COMMIT_MESSAGE:
    required: true

runs:
  using: "composite"
  steps:
    - run: |
            git config user.name ${{ inputs.MAINTAIN_USERNAME }}
            git config user.email ${{ inputs.MAINTAIN_EMAIL }}
            git commit -am "${{ inputs.COMMIT_MESSAGE }}"
            git push
      shell: bash
      