name: Fetch Merged PRs After Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release after which to fetch merged PRs'
        required: true
      branch:
        description: 'Branch to fetch merged PRs from'
        required: true
        default: 'main'

jobs:
  fetch-merged-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Release Date
        id: get-release-date
        run: |
          RELEASE_DATE=$(curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$${{ github.repository }}/releases/tags/${{ github.event.inputs.release }}" | jq -r '.published_at')
          echo "RELEASE_DATE=$RELEASE_DATE" >> $GITHUB_ENV

      - name: Fetch merged PRs after release
        id: fetch-prs
        run: |
          echo "PR Title,PR Link,PR Owner,Jira Task URL" > merged_prs.csv

          PAGE=1

          while : ; do
            response=$(curl -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/$${{ github.repository }}/pulls?state=closed&base=${{ github.event.inputs.branch }}&per_page=100&page=$PAGE")

            echo "$response" | jq -r --arg RELEASE_DATE "$RELEASE_DATE" '
              def construct_jira_url(tid):
                if tid | test("^[A-Za-z]{2,4}-\\d{4,6}$") then "https://elementor.atlassian.net/browse/" + tid
                elif tid | test("^\\d{4,6}$") then "https://elementor.atlassian.net/browse/ED-" + tid
                else "" end;

              .[]
              | select(.merged_at != null and .merged_at > $RELEASE_DATE)
              | {
                  title: (.title | gsub(" \\[([A-Za-z]{2,4}-)?\\d{4,6}\\]"; "")),
                  url: .html_url,
                  login: .user.login,
                  task_id: (.title | match("\\[([A-Za-z]{2,4}-)?\\d{4,6}\\]") | .string | gsub("\\[|\\]"; ""))
                }
              | [ .title, .url, .login, (construct_jira_url(.task_id)) ]
              | @csv
            ' >> merged_prs.csv

            [[ ! $(echo "$response" | grep -Fi Link | grep '<[^>]*>; rel="next"') ]] && break

            ((PAGE++))
          done

      - name: Upload merged PRs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: merged-prs
          path: merged_prs.csv
