name: Image Compare

on: push

jobs:
  run:
    runs-on: ubuntu-16.04
    if: ( startsWith( github.repository, 'elementor/' ) || startsWith( github.repository, 'kobizz/' ) || startsWith( github.repository, 'matipojo/' ) || startsWith( github.repository, 'iNewLegend/' ) || startsWith( github.repository, 'joshmarom/' ) || startsWith( github.repository, 'udidol/' ) || startsWith( github.repository, 'rotemee/' ) )
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          npm install
          npm install backstopjs
      - name: Build Package
        run: |
          npm config set git-tag-version false
          export PLUGIN_VERSION=$(date '+%Y%m%d.%H%M')
          export PACKAGE_VERSION=$(cat package.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[",]//g' \
            | tr -d '[[:space:]]')
          export PLUGIN_ZIP_FILENAME="elementor-${PACKAGE_VERSION}-${PLUGIN_VERSION}-${GITHUB_SHA:0:7}.zip"
          grunt build
          sed -i -E "s/Version: (.*?)/Version: ${PACKAGE_VERSION}-${PLUGIN_VERSION}/g" build/elementor.php
          sed -i -E "s/ELEMENTOR_VERSION', '(.*?)'/ELEMENTOR_VERSION', '${PACKAGE_VERSION}-${PLUGIN_VERSION}'/g" build/elementor.php
          mv build elementor
          zip -r $PLUGIN_ZIP_FILENAME elementor
          curl --fail -F "package=@${PLUGIN_ZIP_FILENAME}" "${{ secrets.DEPLOY_BUILDS_ENDPOINT }}&type=by-commit"
          echo ::set-env name=BUILD_PATH::"builds/by-commit/$(date '+%Y-%m')/${PLUGIN_ZIP_FILENAME}"
          echo ::set-env name=PACKAGE_VERSION::${PACKAGE_VERSION}
      - name: Run Tests
        run: |
          git clone ${{ secrets.BACKSTOP_CONFIG_REPO_URL }} backstop-config
          mkdir -p backstop_data_en_US/
          cp -r backstop-config/reference/ backstop_data_en_US/bitmaps_reference/
          ./node_modules/backstopjs/cli/index.js test --config=backstop-config/backstop.js --count=1 --siteUrl=https://${{ secrets.BACKSTOP_EMULATOR_DOMAIN }} --coreVersion=${BUILD_PATH}
      - name: Before upload..
        run: |
          find backstop_data_en_US -type f -name "*.json" -o -name "*.js" -print0 | xargs -0 sed -i -e 's/${{ secrets.BACKSTOP_EMULATOR_DOMAIN }}/localhost/g'
        if: failure()
      - uses: actions/upload-artifact@master
        if: failure()
        with:
          name: backstop-output
          path: backstop_data_en_US
