name: Qunit

on:
  pull_request:
    paths:
      - '**/*.jsx?'
      - '**/*.tsx?'
      - '**/*.json'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/js-qunit.yml'

  merge_group:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  q-unit:
    runs-on: ubuntu-latest
    name: Qunit - Test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: "Build Scripts"
        run: npm run build:ci
      - name: "Run Qunit"
        run: npx grunt karma:unit
