name: Publish Cloud Version
env:
  WORKING_BRANCH: dev/cloud-publish
# on:
#   workflow_dispatch:
on: [push, pull_request]
jobs:
  poc-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MAINTAIN_TOKEN }}
          ref: $WORKING_BRANCH
      - name: Send slack message
        uses: ./.github/workflows/slack-notify.yml@$WORKING_BRANCH
        with:
          PACKAGE_VERSION: ${{ 'test version 123' }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNELS: ${{ 'C03PMU9HK24' }}
