name: Publish Cloud
# Required secrets for this workflow: MAINTAIN_USERNAME, MAINTAIN_EMAIL, SLACK_TOKEN, SLACK_CHANNELS, MAINTAIN_TOKEN

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Release branch version'
        required: false
      pre_release:
        type: boolean
        description: 'Is this a pre-release?'
        required: false

jobs:
  bump-version:
    runs-on: ubuntu-20.04
    outputs:
      prev_version: ${{ steps.bump_version_step.outputs.prev_version }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MAINTAIN_TOKEN }}
      - name: Get Configuration
        id: configuration
        uses: maork-elementor/json-to-variables@main
        with:
            filename: './.github/workflows/config.json'
            prefix: config
      - name: Test permissions
        uses: ./.github/workflows/permissions
        with:
          ENVIRONMENT: ${{ env.config_deployment_environment }}
          DEPLOYMENT_PERMITTED: ${{ env.config_deployment_permitted }}
          DEPLOYMENT_REPOSITORY_OWNER: ${{ env.config_deployment_repository_owner }}
      - name: Install Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Get next release branch
        uses: ./.github/workflows/get-next-release-branch
        with:
          INPUT_VERSION: ${{ github.event.inputs.version }}
      - name: Checkout next release branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.RELEASE_BRANCH }}
          token: ${{ secrets.MAINTAIN_TOKEN }}
      - name: Get Current SHA
        shell: bash
        run: |
          echo $(git rev-parse HEAD)
          echo "CURRENT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Validate Run Checks
        uses : ./.github/workflows/validate-run-checks
        with:
          TOKEN: ${{ secrets.MAINTAIN_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          CURRENT_SHA: ${{ env.CURRENT_SHA }}
          IGNORE_CHECKS_LIST: "publish-to-cloud,publish_to_jira" # Comma separated list of checks to ignore
      - name: Bump version
        id: bump_version_step
        uses: ./.github/workflows/bump-version
        with:
          CHANNEL: "cloud"
      - name: Push version
        uses : ./.github/workflows/push-new-version
        with:
          MAINTAIN_USERNAME: ${{ secrets.MAINTAIN_USERNAME }}
          MAINTAIN_EMAIL: ${{ secrets.MAINTAIN_EMAIL }}
          COMMIT_MESSAGE: "Bump ${{ env.PACKAGE_VERSION }}"
  publish-to-cloud:
    needs: bump-version
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MAINTAIN_TOKEN }}
      - name: Install Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Get next release branch
        uses: ./.github/workflows/get-next-release-branch
        with:
          INPUT_VERSION: ${{ github.event.inputs.version }}
      - name: Checkout next release branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MAINTAIN_TOKEN }}
          ref: ${{ env.RELEASE_BRANCH }}
      - name: Install Dependencies
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').last_cloud_version")
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
          npm ci
      - name: Build plugin
        uses: ./.github/workflows/build-plugin
        with:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
          UPDATE_VERSIONS_SCRIPT_PATH: "./.github/scripts/update-version-elementor-php.sh"
          BUILD_SCRIPT_PATH: "./.github/scripts/build-zip.sh"
      - name: Upload zip file to GitHub actions artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PLUGIN_ZIP_FILENAME }}
          path: ${{ env.PLUGIN_ZIP_PATH }}
          if-no-files-found: error
      - name: Create Git tag
        uses : ./.github/workflows/create-git-tag
        with:
          MAINTAIN_USERNAME: ${{ secrets.MAINTAIN_USERNAME }}
          MAINTAIN_EMAIL: ${{ secrets.MAINTAIN_EMAIL }}
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
      - name: Generate changelog
        uses : ./.github/workflows/generate-changelog
        with:
          TOKEN: ${{ secrets.MAINTAIN_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          HEAD_BRANCH_NAME: v${{ env.PACKAGE_VERSION }}
          BASE_TAG_NAME: v${{ needs.bump-version.outputs.prev_version }}
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          files: elementor-*.zip
          prerelease: ${{ github.event.inputs.pre_release }}
          body_path: temp-changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.MAINTAIN_TOKEN }}
      - name: Send slack message
        uses: ./.github/workflows/slack-notify
        with:
          MESSAGE: "@here Elementor ${{ env.PACKAGE_VERSION }} has been released! Saddle up partners! :tada:"
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNELS: ${{ secrets.SLACK_CHANNELS }}
