name: Elementor-ScreenShotter

on: [ push, pull_request ]

jobs:
  run:
    runs-on: ubuntu-16.04
    timeout-minutes: 20
    env:
      screenshotter_config_path: ${{ github.workspace }}/tests/screenshotter/config.js
    strategy:
      fail-fast: false
      matrix:
        wordpress_versions: [ 'latest' ]
    name: WordPress ${{ matrix.wordpress_versions }}
    steps:
      - name: Startup MySQL service
        run:  sudo /etc/init.d/mysql start
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Install Elementor-ScreenShotter
        run: | ##### TO DO: Remove all sudo
          sudo ln -sf /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm
          sudo chown -R $USER /usr/local/lib/node_modules
          sudo chown -R $USER /usr/local/bin/
          npm i -g @elementor/screenshotter
      - name: Install Dependencies
        run: |
          elementor-screenshotter-install --config=${screenshotter_config_path} --debug=true
      - name: Import Templates
        run: |
          elementor-screenshotter-import-templates --config=${screenshotter_config_path} --debug=true
      - name: Build Package & Run Test
        run: |
          elementor-screenshotter-run-test --config=${screenshotter_config_path} --debug=true --deepDebug=true
      - uses: actions/upload-artifact@master
        if: failure()
        with:
          name: backstop-output
          path: /tmp/wordpress/backstop_data
